wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.17.9
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1725914524
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      3:
      - 23
      4: 3.9.6
      5: 0.17.9
      6: 4.44.2
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
